### ISSUE TITLE
Question: is it possible to anonymize  the Patient's ID with a specific ID (ie. enconding)

### ISSUE THREAD

**Issue by raluca-san** [chop-dbhi/dicom-anon#26]

**Comment by jeffmax** [comment]
@raluca-san do you mean pre specify a mapping from identified patient id -> specific de-identified id for all patient ids prior to calling dicom-anon?

**Comment by raluca-san** [comment]
yes. I am going to re-phrase it,

- is it possible to pre-specify a mapping from identified patient id --> specific de-indentified id for a single patient (the clinic has already assigned specific trial ids for the patient)

so, when calling dicom_anon.py could I specify a specific patient_id/patient_name in the --spec/ opts?

**Comment by jeffmax** [comment]
Sorry for the late response, I was thinking that it might be possible to pre-populate the identity sqlite database with the mapping by creating the "patientid" table, but I don't think it would work because it is dependent on the study_ui_pk (https://github.com/chop-dbhi/dicom-anon/blob/master/dicom_anon.py#L433). It looks like this is not possible without modifying the code or replacing the patient ids with the mapped values prior to running the anonymizer and using a custom spec_file.
